---
- name: Configure Raddit App Instance
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Install python for Ansible to work
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

  tasks:
    - name: Install Ruby and Bundler
      apt:
        name: ruby-full build-essential
      gem:
        name: bundler
        state: present
        user_install: no
        include_doc: no

    - name: Install MongoDB
      apt_key:
        id: D68FA50FEA312927
        keyserver: keyserver.ubuntu.com
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2
      apt:
        update_cache: yes
        state: present
        name: mongodb-org

    - name: Start MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Download Unit File for Raddit
      get_url:
        url: https://gist.githubusercontent.com/Artemmkin/ce82397cfc69d912df9cd648a8d69bec/raw/7193a36c9661c6b90e7e482d256865f085a853f2/raddit.service
        dest: /etc/systemd/system/raddit.service
